### ISSUE TITLE
Crashes on Android O as it doesn't request permissions at run time

### ISSUE THREAD

**Issue by anolivetree** [karino2/MeatPieDay#2]
Needs to request a permission using ActivityCompat.requestPermissions().

10-15 23:30:29.900 13434-13434/karino2.livejournal.com.meatpieday W/System.err: io.reactivex.exceptions.OnErrorNotImplementedException: /storage/emulated/0/MeatPieDay/share_tmp/(New Book).ipynb (Permission denied)
10-15 23:30:29.900 13434-13434/karino2.livejournal.com.meatpieday W/System.err:     at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:704)
10-15 23:30:29.900 13434-13434/karino2.livejournal.com.meatpieday W/System.err:     at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:701)
10-15 23:30:29.900 13434-13434/karino2.livejournal.com.meatpieday W/System.err:     at io.reactivex.internal.observers.ConsumerSingleObserver.onError(ConsumerSingleObserver.java:45)
10-15 23:30:29.901 13434-13434/karino2.livejournal.com.meatpieday W/System.err:     at io.reactivex.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run(SingleObserveOn.java:79)
10-15 23:30:29.901 13434-13434/karino2.livejournal.com.meatpieday W/System.err:     at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:109)
10-15 23:30:29.901 13434-13434/karino2.livejournal.com.meatpieday W/System.err:     at android.os.Handler.handleCallback(Handler.java:789)
10-15 23:30:29.901 13434-13434/karino2.livejournal.com.meatpieday W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:98)
10-15 23:30:29.901 13434-13434/karino2.livejournal.com.meatpieday W/System.err:     at android.os.Looper.loop(Looper.java:164)
10-15 23:30:29.901 13434-13434/karino2.livejournal.com.meatpieday W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6541)
10-15 23:30:29.901 13434-13434/karino2.livejournal.com.meatpieday W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
10-15 23:30:29.901 13434-13434/karino2.livejournal.com.meatpieday W/System.err:     at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
10-15 23:30:29.901 13434-13434/karino2.livejournal.com.meatpieday W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
10-15 23:30:29.902 13434-13434/karino2.livejournal.com.meatpieday W/System.err: Caused by: java.io.FileNotFoundException: /storage/emulated/0/MeatPieDay/share_tmp/(New Book).ipynb (Permission denied)
10-15 23:30:29.902 13434-13434/karino2.livejournal.com.meatpieday W/System.err:     at java.io.FileOutputStream.open0(Native Method)
10-15 23:30:29.902 13434-13434/karino2.livejournal.com.meatpieday W/System.err:     at java.io.FileOutputStream.open(FileOutputStream.java:287)
10-15 23:30:29.902 13434-13434/karino2.livejournal.com.meatpieday W/System.err:     at java.io.FileOutputStream.<init>(FileOutputStream.java:223)
10-15 23:30:29.902 13434-13434/karino2.livejournal.com.meatpieday W/System.err:     at java.io.FileOutputStream.<init>(FileOutputStream.java:171)
10-15 23:30:29.902 13434-13434/karino2.livejournal.com.meatpieday W/System.err:     at java.io.FileWriter.<init>(FileWriter.java:90)
10-15 23:30:29.902 13434-13434/karino2.livejournal.com.meatpieday W/System.err:     at karino2.livejournal.com.meatpieday.Exporter.saveBookToFile(Exporter.java:86)
10-15 23:30:29.902 13434-13434/karino2.livejournal.com.meatpieday W/System.err:     at karino2.livejournal.com.meatpieday.Exporter.exportBookForShare(Exporter.java:41)
10-15 23:30:29.903 13434-13434/karino2.livejournal.com.meatpieday W/System.err:     at karino2.livejournal.com.meatpieday.BookSender.exportBookForShare(BookSender.java:41)
10-15 23:30:29.903 13434-13434/karino2.livejournal.com.meatpieday W/System.err:     at karino2.livejournal.com.meatpieday.BookSender.lambda$sendTo$0(BookSender.java:53)
10-15 23:30:29.903 13434-13434/karino2.livejournal.com.meatpieday W/System.err:     at karino2.livejournal.com.meatpieday.BookSender$$Lambda$1.call(Unknown Source:4)
10-15 23:30:29.903 13434-13434/karino2.livejournal.com.meatpieday W/System.err:     at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:35)
10-15 23:30:29.903 13434-13434/karino2.livejournal.com.meatpieday W/System.err:     at io.reactivex.Single.subscribe(Single.java:2703)
10-15 23:30:29.903 13434-13434/karino2.livejournal.com.meatpieday W/System.err:     at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
10-15 23:30:29.903 13434-13434/karino2.livejournal.com.meatpieday W/System.err:     at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:451)
10-15 23:30:29.903 13434-13434/karino2.livejournal.com.meatpieday W/System.err:     at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:61)
10-15 23:30:29.904 13434-13434/karino2.livejournal.com.meatpieday W/System.err:     at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:52)
10-15 23:30:29.904 13434-13434/karino2.livejournal.com.meatpieday W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
10-15 23:30:29.904 13434-13434/karino2.livejournal.com.meatpieday W/System.err:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
10-15 23:30:29.904 13434-13434/karino2.livejournal.com.meatpieday W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
10-15 23:30:29.904 13434-13434/karino2.livejournal.com.meatpieday W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
10-15 23:30:29.904 13434-13434/karino2.livejournal.com.meatpieday W/System.err:     at java.lang.Thread.run(Thread.java:764)

**Comment by karino2** [comment]
Yes, it's bug. N or higher user need to grant permission from setting as a work around.
